server {
    listen {{NGINX_HTTP_PORT}};
    server_name {{SERVER_NAME}};
    return 301 https://$host$request_uri;
}

server {
    listen {{NGINX_HTTPS_PORT}} ssl;
    server_name {{SERVER_NAME}};

    ssl_certificate {{SSL_CERT_PATH}};
    ssl_certificate_key {{SSL_KEY_PATH}};
    add_header X-Content-Type-Options nosniff always;
    add_header Referrer-Policy strict-origin-when-cross-origin always;

    location ~* \.bak {
        deny all;
    }

    location /monitor {
        proxy_pass http://{{MONITOR_BIND_HOST}}:{{MONITOR_BIND_PORT}};
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }

    location / {
        proxy_pass http://{{APP_BIND_HOST}}:{{APP_BIND_PORT}};
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }
}
